### ISSUE TITLE
Remove image from cloudinary

### ISSUE THREAD

**Issue by harshmangalam** [harshmangalam/hydrogen-nodejs-server#1]
When any image is uploaded it saved into cloudinary add api to remove image from cloudinary.

**Comment by arsen1c** [comment]
Hi, does that mean we need to create a new delete endpoint that will take an image id as a parameter and delete the image with that image id from Cloudinary?

**Comment by harshmangalam** [comment]
You will receive publicId of image as params use this public id with node cloudinary sdk to destroy image.

**Comment by arsen1c** [comment]
Cool, I am working on it.

**Comment by arsen1c** [comment]
I would recommend you to try running this commit locally before merging @harshmangalam

**Comment by harshmangalam** [comment]
Yes adding i was busy to add  this changes to production and applying secrets tu Heroku so taken some time

**Comment by harshmangalam** [comment]
Issues  resolved successfully
