### ISSUE TITLE
Add admin info in group 

### ISSUE THREAD

**Issue by harshmangalam** [harshmangalam/hydrogen-nodejs-server#10]
When returning  group info also add admin info
- firstName
- id
- profilePic

**Comment by RohitShelke10** [comment]
I'd like to do this!

**Comment by harshmangalam** [comment]
Okay

**Comment by RohitShelke10** [comment]
This is already there in fetchGroupDetails @harshmangalam

**Comment by harshmangalam** [comment]
Yes add in other group fetch routes

**Comment by RohitShelke10** [comment]
@harshmangalam created a pull request

**Comment by harshmangalam** [comment]
Fixed by @RohitShelkeBot
