### ISSUE TITLE
Add group admin details

### ISSUE THREAD

**Issue by harshmangalam** [harshmangalam/hydrogen-nodejs-server#2]
Inside group api also return group admin details  

- id 
- firstName

**Comment by abhinavjoshicse** [comment]
Hey! I would like to contribute in this, Please assign this to me.

**Comment by Trishank-K** [comment]
Hey! I would like to contribute in this, Please assign this to me.

**Comment by Trishank-K** [comment]
![Screenshot 2024-10-01 103829](https://github.com/user-attachments/assets/f3cef167-cfed-4509-809b-f10a1fcbb0b7)

Hey! is this not working?
I think it already returns id and firstName

Check this out:
https://github.com/harshmangalam/hydrogen-nodejs-server/blob/master/src/controllers/group/fetchGroupDetails.js#L17-L23

**Comment by harshmangalam** [comment]
Thanks @Trishank-K  then it seems to like the frontend issues not able to show up the admin data
