### ISSUE TITLE
Add api to delete user account

### ISSUE THREAD

**Issue by harshmangalam** [harshmangalam/hydrogen-nodejs-server#3]
Add new api inside users to delete their account permanently also release all resources related to that specific user.

**Comment by gokhalevedant06** [comment]
Hi @harshmangalam, I would like to work on this issue

**Comment by gokhalevedant06** [comment]
Hello @harshmangalam, can you help me with the installation of the project. It will be better if you mention installation steps in the readme

**Comment by harshmangalam** [comment]
Sure i will add

**Comment by harshmangalam** [comment]
Now you can proceed with installation added in readme

**Comment by gokhalevedant06** [comment]
I have setup postgreSQL but I am getting some error in prisma files
![image](https://user-images.githubusercontent.com/79954118/193404343-a3cff0eb-7939-4e02-a510-8bbb3e034b5c.png)

**Comment by harshmangalam** [comment]
May be this will help you https://www.prisma.io/docs/reference/api-reference/error-reference#p1012

**Comment by spykelionel** [comment]
This looks good

**Comment by Edqe14** [comment]
Hey, I would like to work on this issue
