### ISSUE TITLE
Add createdAt field in user

### ISSUE THREAD

**Issue by harshmangalam** [harshmangalam/hydrogen-nodejs-server#8]
Select createdAt field when sending user data in prisma query.

**Comment by RohitShelke10** [comment]
I would like to do this task!

**Comment by harshmangalam** [comment]
Okay

**Comment by RohitShelke10** [comment]
@harshmangalam for which apis should createdAt be sent?

**Comment by harshmangalam** [comment]
`/users/:userId` for user details route

**Comment by RohitShelke10** [comment]
Done! Please accept pull request. @harshmangalam

**Comment by harshmangalam** [comment]
Fixed by @RohitShelkeBot
