### ISSUE TITLE
Add api to remove group notifications

### ISSUE THREAD

**Issue by harshmangalam** [harshmangalam/hydrogen-nodejs-server#9]
Add an api to clear group notifications.

**Comment by detronetdip** [comment]
if this is open to be picked up, I am interested.

**Comment by harshmangalam** [comment]
Sure

**Comment by detronetdip** [comment]
hey @harshmangalam  can you please explain me how the group notification currently works so that I can have a better understanding.

**Comment by harshmangalam** [comment]
When any user will create new group then a notification (type=`GROUP`) will be created and will send to all their friends. And when any new group post will be added then all members will get notification of type `GROUP`

**Comment by harshmangalam** [comment]
Create new api in  notification route that can remove notification of type `GROUP` and related to current user

**Comment by harshmangalam** [comment]
You can follow the same way remove notification is added in notifications controller.

**Comment by detronetdip** [comment]
![Screenshot from 2022-10-07 20-51-56](https://user-images.githubusercontent.com/64276906/194590209-6d453543-798e-4e30-920f-3947c0eb940b.png)

I am getting this errors. Can you please tell me what is going wrong?

**Comment by harshmangalam** [comment]
May be this will help you https://github.com/prisma/prisma/issues/8320

**Comment by detronetdip** [comment]
There is no space related issues.
See the below ss. I am getting this error.
![Screenshot from 2022-10-08 10-04-25](https://user-images.githubusercontent.com/64276906/194688475-0b6811f1-7b70-432d-b905-c356b80f1c78.png)

**Comment by harshmangalam** [comment]
Which prisma version are you using ?

**Comment by detronetdip** [comment]
4.3.1

**Comment by harshmangalam** [comment]
There is breaking changes in schema in v4 . This project is using  `prisma": 3.9.2`

**Comment by fekete965** [comment]
I am happy to pick this issue up if it hasn't been addressed in the past.

**Comment by harshmangalam** [comment]
Sure @fekete965
